### ISSUE TITLE
nbd

### ISSUE THREAD

**Issue by patatetom** [msuhanov/Linux-write-blocker#10]
hello,

in addition to the patch for the kernel, what do you think of a udev rule that builds a special node that gives access to the original device through an nbd layer ?

suppose `/dev/sdb` is the original device and Qemu is available : after loading the `nbd` kernel module, the command `qemu-img --read-only --snapshot --connect /dev/nbd0 /dev/sdb` allows indirect access to `/dev/sdb*` through `/dev/nbd0*` and allows to absorb any uncontrolled writings.

the `--read-only` option can even be omitted if changes are needed, for example, for a simple repair of the file system to allow access to the data...

regards, lacsaP.

**Comment by msuhanov** [comment]
If this method works as expected, then it should produce the same effects as using a read-only loop device. With the same problems (like a file system driver opening an original block device if an external journal is used).

**Comment by patatetom** [comment]
yes, unlike the read-only option which may not be used and give a desired write access to the layer.
maybe it would be possible, in the udev rule, to "hide" the original device after linking or allow only nbd proccess (systemd/cgroups) ?

**Comment by msuhanov** [comment]
> yes, unlike the read-only option which may not be used and give a desired write access to the layer

A loop device can be read-write too.

> maybe it would be possible, in the udev rule, to "hide" the original device after linking or allow only nbd proccess (systemd/cgroups) ?

I think this is impossible, because some dangerous things (like picking a block device using metadata from a superblock of another block device) originate from the kernel.

**Comment by patatetom** [comment]
> I think this is impossible...

yes, it should at least be very difficult....

> A loop device can be read-write too.

yes, but the advantage of nbd over loop in the case of read-write access is that the writings are carried by the snapshot layer and not by the linked device : if I fix the file system carried by the nbd0p1 pseudo-partition, no change is made on sda1 while if I fix loop0p1, the corrections are made on sda1.
_it's a good technique to be able to change things without changing anything ;-)_

thank you for these exchanges.
