### ISSUE TITLE
Usage problem

### ISSUE THREAD

**Issue by ExonakiDev** [msuhanov/Linux-write-blocker#13]
Hi Maxim,

I am trying to apply the patch on my Raspberry Pi
```
Linux raspberrypi 5.10.103-v7+ #1530 SMP Tue Mar 8 13:02:44 GMT 2022 armv7l GNU/Linux
```
But I am not able to do so. Can you please help me with the same?

This is the issue that I am facing:
```
pi@raspberrypi:~/Linux-write-blocker/kernel $ patch < linux-4.10-enforce-ro.patch
can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- linux-master/block/blk-core.c      2016-12-16 22:23:34.000000000 +0300
|+++ linux-master-patched/block/blk-core.c      2016-12-18 15:12:54.837220465 +0300
--------------------------
```

**Comment by patatetom** [comment]
hi,

you can eventually do it manually :

- search for the string `/* Older lvm-tools actually trigger this */` in `src/linux-xxx/block/blk-core.c`
- replace next line `return false;` with `return true;`

regards, lacsaP.

---

_example for linux-5.10.19 :_
```diff
--- a/src/linux-5.10.19/block/blk-core.c
+++ b/src/linux-5.10.19/block/blk-core.c
@@ -706,7 +706,7 @@
               "Trying to write to read-only block-device %s (partno %d)\n",
            bio_devname(bio, b), part->partno);
        /* Older lvm-tools actually trigger this */
-       return false;
+       return true;
    }

    return false;
```

**Comment by msuhanov** [comment]
Hello.

My patch doesn't support newer versions of the kernel.
The patch mentioned above (you can take it here: https://github.com/vitaly-kamluk/Linux-write-blocker/blob/master/kernel/linux-5.4-enforce-ro.patch) should work, although I didn't validate it.
