### ISSUE TITLE
Kernel patch 

### ISSUE THREAD

**Issue by denniszheng497** [msuhanov/Linux-write-blocker#4]
Hi there,
is your patch 4.10 compatible with 4.4.0. I tried to patch it to my blk-core.c file, it didn't work . Also tried apply your patch to it manually . However, my blk-core.c file looks slightly different , so my question is does kernel 4.4.0 still need your patch to fix those bugs ? or 4.4.0 doesn't need that patch anymore ? if it still needs that patch , can you please help me to apply to it ?

many thanks

**Comment by msuhanov** [comment]
Hello.

The kernel version 4.4.0 requires the patch, and this version is supported, just use the older patch (linux-3.15.1-enforce-ro.patch).

**Comment by denniszheng497** [comment]
Hi there,


thank you so much for your help . I've manually applied the patch to the blk-core.c file . However , I am not very confident about if it's been applied correctly , are you able to check the following codes for me to see if it's correct please . Also last question is why are we using the older patch for 4.40? is there a reason for this ?



generic_make_request_checks(struct bio *bio)
{
struct request_queue *q;
int nr_sectors = bio_sectors(bio);
int err = -EIO;
char b[BDEVNAME_SIZE];
struct hd_struct *part;

might_sleep();

if (bio_check_eod(bio, nr_sectors))
goto end_io;

q = bdev_get_queue(bio->bi_bdev);


           if (unlikely(!q)) {
printk(KERN_ERR
      "generic_make_request: Trying to access "
"nonexistent block-device %s (%Lu)\n",
bdevname(bio->bi_bdev, b),
(long long) bio->bi_iter.bi_sector);
goto end_io;
}

part = bio->bi_bdev->bd_part;
if (should_fail_request(part, bio->bi_iter.bi_size) ||
   should_fail_request(&part_to_disk(part)->part0,
bio->bi_iter.bi_size))
goto end_io;

/*
* If this device has partitions, remap block n
* of partition p to block n+start(p) of the disk.
*/
blk_partition_remap(bio);

if (bio_check_eod(bio, nr_sectors))
goto end_io;

/*
* Filter flush bio's early so that make_request based
* drivers without flush support don't have to worry
* about them.
*/
if ((bio->bi_rw & (REQ_FLUSH | REQ_FUA)) && !q->flush_flags) {
bio->bi_rw &= ~(REQ_FLUSH | REQ_FUA);
if (!nr_sectors) {
err = 0;
goto end_io;
}
}

       /*
        * Block write and discard commands going to a read-only device.
        * We do this because kernel drivers often lack necessary checks
        * and send write/discard commands to read-only block devices.
        */

       if (unlikely((bio->bi_rw & (REQ_WRITE | REQ_WRITE_SAME | REQ_DISCARD))
                       && bdev_read_only(bio->bi_bdev))) {
               pr_warn("unexpected %s command to %s blocked\n",
                       (bio->bi_rw & REQ_DISCARD) ? "discard" : "write",
                       bdevname(bio->bi_bdev, b));
               goto end_io;
       }


if ((bio->bi_rw & REQ_DISCARD) &&
   (!blk_queue_discard(q) ||
    ((bio->bi_rw & REQ_SECURE) && !blk_queue_secdiscard(q)))) {
err = -EOPNOTSUPP;
goto end_io;
}



________________________________

**Comment by msuhanov** [comment]
It seems that everything is okay with the code, try to build the kernel.

> Also last question is why are we using the older patch for 4.40? is there a reason for this ?

The kernel version 4.4.* has a block subsystem compatible with the patch for the kernel version 3.15.1. Some major changes were made in the kernel version 4.9.*, which made the older patch incompatible with this version. Also, more changes were made in the kernel version 4.10.*, so I had to release a new patch that is currently compatible with the kernel versions >=4.10 (and the version 4.9 is not supported).
