### ISSUE TITLE
udev

### ISSUE THREAD

**Issue by patatetom** [msuhanov/Linux-write-blocker#8]
hello,

what do you think of a "live" Linux rebuilt with this udev rule :

```bash
cat /etc/udev/rules.d/09-readonly.rules

KERNEL=="sd*", SUBSYSTEM=="block", RUN+="/usr/local/sbin/rodev /dev/%k"
```

and this shell script :

```bash
cat /usr/local/sbin/rodev

#!/usr/bin/bash

[ ! "${1}" ] && echo "error: device missing" >/dev/stderr && exit 1
[ "${2}" ] && echo "error: too many devices" >/dev/stderr && exit 1

[[ "${1}" =~ ^"${livelinux::-1}" ]] && exit

chmod 440 "${1}"
blockdev --setro "${1}"
```

?

regards, lacsaP.

**Comment by msuhanov** [comment]
The udev rule will skip block devices with names like _mmcblk*_ (and anything else different from _sd*_).
It is recommended to use the udev rule and scripts from this repository.

**Comment by patatetom** [comment]
I had not searched your repository before my question: indeed, your udev rule is much more relevant !
thank you for your return and your work.
good continuation, lacsaP
