### ISSUE TITLE
usage help

### ISSUE THREAD

**Issue by klango** [msuhanov/Linux-write-blocker#9]
Hi Maxim, thankx for your efforts on this-
About the usage, do you mount the partition (after running blockdev --setro /dev/sdb*) still using ro,loop? 

or by blocking the device thru blockdev is enough to avoid writing into sdb*?

Best

**Comment by msuhanov** [comment]
> or by blocking the device thru blockdev is enough to avoid writing into sdb*?

Yes, it's enough.

**Comment by msuhanov** [comment]
When this patch was applied to the kernel, of course.

**Comment by klango** [comment]
After patched indeed.
But then does the disk has to be mounted ro,loop or simply mounting automatically rw is already write blocked? After running blockdev of course.

**Comment by msuhanov** [comment]
Yes, it's protected from writes.
